name: CI
on: [push]

jobs:

# сборка проекта
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: sudo apt-get install -y libgtest-dev gcovr lcov
      - run: sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
      - run: sudo tar -xf release-1.7.0.tar.gz && rm -rf release-1.7.0.tar.gz
      - run: cd googletest-release-1.7.0
      - run: sudo cmake
      - run: sudo make googletest-release-1.7.0
      - run: sudo mkdir build && cd build && sudo cmake .. && sudo make

# покрытие
  gcovr:
    needs: build-project
    name: Gcovr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: sudo apt-get install -y libgtest-dev gcovr lcov
      - run: sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
      - run: sudo tar -xf release-1.7.0.tar.gz && rm -rf release-1.7.0.tar.gz
      - run: cd googletest-release-1.7.0
      - run: sudo cmake
      - run: sudo make googletest-release-1.7.0
      - run: sudo mkdir build && cd build && sudo cmake .. && sudo make
      - run: sudo ./build/test/test_detect
      - run: sudo gcovr -r .. --html --html-details -o cov.html
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cov.html
